### ISSUE TITLE
1w[ANN] 5 月 ZoomQuiet 上海线下聚会

### ISSUE THREAD

**Issue by leilayanhui** [DebugUself/playground#11]
# ZoomQuiet 上海线下面基会~
逮着大妈来上海的机会, 小伙伴一起聚下, 向信息源头—— ZoomQuiet 学习如何自怼

上海嗯哼现场录音和部分录像:

- 链接:https://pan.baidu.com/s/1cfLfWMA8LaLvDkzBEPn5UQ  
- 密码:wlhv
- 作业:
    + 回忆总结 got 到的 top3 嗯哼点 (大于 512 字)
    + 并针对当前想作的事儿, 给出对应改进规划
    + 发布在自有发布渠道, 回复 Issue 给出访问链接
    + 或是直接回复 Issue 给出

## 时间地点
- 时间: 5/30 周三晚 19:00  
- 地点: [星巴克 (名仕苑店)](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjNxN695p_bAhUfCDQIHVbBB5AQFggmMAA&url=http%3A%2F%2Fwww.dianping.com%2Fshop%2F18477682&usg=AOvVaw3KBJ_u-i8p3xtCfho3rLPM)   广元西路98号3-4室, 地铁1/9/11号线 徐家汇站
- 联系人: 蕙蕙  微信号: Leila_yh
- 微信群: 201805 大妈面基会, 二维码见下

名仕苑店离地铁稍微远点, 港汇\美罗城怕没位子. 欢迎提供徐家汇地区的聚会地点.

## 活动流程:
* 19:00 ~ 19:30 自我介绍
* 19:30 ~ 21:30 向大妈提问
* 聚会过程全程录音, 会分享至网盘

## 参与方式
确定来参加的回复此 issue 

- 名号: 
- 微信号: 
- 到达时间: 
- 怎么认识大妈的
- 最想问大妈: 
- 上限 10 人, 若有的话

**Comment by leilayanhui** [comment]
名号: 蕙蕙
微信号  Leila_yh
到达时间: 19:00
怎么认识大妈的: py103
最想问大妈: 如何知道自己应掌握什么知识点？

**Comment by ghost** [comment]
- 名号: 周绪龙
- 微信号: zl__01
- 到达时间: 19:00前-21:25离开返常州
- 怎么认识大妈的: py103
- 最想问大妈: 如何培养与保护小孩子的编程兴趣(4岁男)？培养要走哪些步骤？学习哪些科目？自己应该怎样陪伴他？

**Comment by erdongheng** [comment]
名号:耳东恒
到达时间:19:15
怎么认识大妈的：开智某篇文章里的介绍
最想问大妈:
1.我学经管，做财务，编程基础零。编程对我来说就像魔法，浩瀚神秘。想问魔法师先生，这魔法是否在某个学习它的时刻让你着迷？那些喜欢这魔法的人一般为什么喜欢它呢？
2.能否推荐几本编程相关的书，一者引起对编程的兴趣和信心，二者养成良好的编程习惯，三者一窥编程的疆域风貌？
3.学编程，于我而言要有兴趣，更需要有信心。我的业余时间已不多（开智的课都要时间），自觉编程要记的东西也不少，因此信心不大。是否有哪些事实，可以稍微地激起一些信心呢？
4.学习编程是否使你的思维方式、生活方式，变得和没学习编程时不一样？如果有，又是什么样的不一样？
5.如果只是看教材、写代码，学习编程可能会比较枯燥。有哪些好的形式能让这个学习过程更有意思点？

**Comment by ZoomQuiet** [comment]
@erdongheng 是也乎,(￣▽￣)

> ..怎么认识大妈的：开智某篇文章里的介绍

- 具体哪篇文章?
- 此文章你是如何进行收藏管理的?
- 文章看了几次? 如何证明? 有进一步的笔记/衍生输出?
- 类似所有自己认同的文章/文件/软件/录音/电影/帐号/... 又都是如何日常管理和提取使用的?
    + 以及再应用过程中有形成什么自己专用的习惯/流程/工具?
    + 对应的输出又有什么固定的渠道?
        * 即, 自己对目标知识的学习/掌握/应用/...
        * 是如何快速反馈给自己的圈子的?
        * 这种圈子日常是如何经营的?
        * ...

以及其它相关的42个问题...

认真回答了, 就知道什么是编程了...

**Comment by lffaye0612** [comment]
名号: 李斐斐
微信号 lffaye0708
到达时间: 18:30
怎么认识大妈的: 通过李广鹤介绍“怼圈”
最想问大妈: 如何进行时间管理？还有想问一下每天复盘的具体执行方法？还有想知道如何提高自己也能问出上述“其他相关42个问题”的能力？（会不会被打o(╯□╰)o）

**Comment by yanzhiw** [comment]
名号: 刘和宇
微信号: yanzhiwang
到达时间: 19:00前
怎么认识大妈的: py103
最想问大妈: 目前我的工作一部分是面向白领的金融培训，回访的时候我发现很多用户在细节中会加入自己的一些错误观念或理解。我在Python的学习中时也有很多时候会有这种情况。这是否有一些体系方法可以解决或者尽量解决？

**Comment by linfeng365** [comment]
听录音后,记的几个要点
5月30日 上海 大妈见面会 | linfeng365  
http://linfeng365.com/blog/shanghaiMeeting20180530.html

**Comment by leilayanhui** [comment]
## 回忆 Top3
先来个屎稿
1. 达到目标不重要, 达到状态才重要
	- 学习编程不重要, 编程状态才重要 
	- 时间管理/记录不重要, 进行记录才重要
	- 我要做什么不重要, 我「正在做」才重要
2. 理性思维
刨根问底式提问, 什么是什么/为什么, 基本追问到第三层就能找到根源.
3. 全局认识
全世界最大的 xx 是什么? 整个历史上 xx 是怎么样的? 不断提升量级来认识某一东西

## 如何知道要学什么?
算法/数据结构是什么? 有什么用? 为什么重要? 怎么用的? 提升多少?

**Comment by ghost** [comment]
> 2018-05-30 上海星巴克（名仕院店）ZoomQuiet 线下聚会

## 回忆总结 get 到的嗯哼点

- 我的提问：如何培养与保护小孩子的编程兴趣(4岁男)？培养要走哪些步骤？学习哪些科目？自己应该怎样陪伴他？
    + 如果目前的编程技术，在未来依然是必备技能，那么整个社会自然会培养孩子的。
    + 关联科目：英语阅读水平很重要，这个当下可以开始着手。
    + 想要陪伴小孩成长，自己得会，否则他不带你玩儿。

- 帮胖狐问的问题：从python到javascript,1年多来一直在不停折腾，越是向前，越来越感觉缺乏的知识点很多，比如算法数据结构等等，开始怀疑在36岁"高龄"转行前端程序员的决定，焦虑不安。
    + 大妈说其实每个人面临的环境问题都一样，世界上曾经和现在出现的编程语言超过1500种，程序员跨语言学习是常态。
    + 焦虑怎么办？写作、表达、找同类、找反馈、找成就感。

- **大妈的高效率、强科学主义是怎样炼成的？**
    + 昨天当面见到大妈：一边答疑，一边录音，一边计时且分段计时，一边开zoom且每小时更新一次且将链接发群里，一边给每个同学拍照，一边根据学员的表达提炼核心词汇和句子甚至还记得某个词语说了多少次，根据关键词经过思考怼N个问题，而且自己的aTimeLogger计时还非常精确......
    + 这里体会到老阳一直在说的「原则正确」不如「细节正确」，大妈的习惯已形成肌肉记忆，从2013年至今 aTimeLogger 详细记录时间，背后的动力是什么？我想不到，也不需要想，因为每个人的动机、性格都不一样。我应该问自己：为什么大妈能做到，我却做不到？是我不热爱？没毅力？焦躁静不下来？
    + 行动技巧：不见得每一个小行动，都能带来一样的价值和成就，有的信息甚至是白忙活，但量变才会质变，科学操作主义强调的是行动。假设、验证，只能从行动中成长。


## 针对当前想作的事儿，给出相应改进计划

- 最想做、而一直没有做好的事：学英语
    + 以往的借口：没时间、太难了、过了掌握语言的最佳年龄、没有使用环境、需要学习的东西太多、不会英语也不会死......
    + 改进计划1：Anki 找出最常用7000词汇清单，每天至少学习30分钟，打卡计时。
    + 改进计划2：小孩子英语课上的单词，我都学会，且练到最标准发音，和小孩互动，引发他的兴趣。
    + 改进计划3：手机上的英文 App 使用起来，比如 workflow 。
    + 改进计划4：请教英语学霸同学赵赵，要一份成年人学习计划，以及绕不过去的最小行动。

**Comment by lffaye0612** [comment]
>大妈面基回忆
### 1.震撼点记录
* Fake it until you make it.
* 输出倒逼输入，考虑写出如何教不会编程的人学会一门编程语言，并且在这个过程中可以得到别人的反馈与肯定。
* 编程是最简单，他不会变幻莫测不需要反复琢磨，按照既定的逻辑给他输入，他一定会按照期待给出输出，只有1和0两个状态，没有中间态没有模糊地带。
* 更多的困难是自己想出来的，我们总是习惯假想困难，困难是有的，但是是在你真正完成并且回头看的时候你才会真正知道困难所在，也会知道困难并没有想象中那么难。
* 任何事情从做饭到编程到恋爱，都是统一的解决问题的方法：认清主要矛盾，勇于揭露主要矛盾，快速解决。

### 2.反思自己的问题
* 大妈问我的行为，我却总是在回答我的感受，这一发现让我震惊。为什么会出现这样的情况，我想一方面是因为我确实并没有真正的行动，另一方面就是我潜意识里太在意并且活在自己的感受里。这样很容易对世界对周边产生一种错误的认知，把自己完全封闭在这个错误的认知里。另外这个过程也透露了我沟通方面的问题。（在工作在恋爱中应该都有影响）
* 昨晚确实第一次听到“Fake it until you make it",非常喜欢。我一直认为做人应该正直坦荡，不能说一句假话，以致从读书到工作以来都是会做5分，绝对只说3分，从来不敢妄言。其实这样的处事并不利于我的工作生活，我慢慢的也感觉到有些不对劲，却不知道哪里不对劲。昨晚终于知道了。有时候需要一点不要脸不要怕的精神，怕什么呢，装着装着说不定就真的会了呢！
* 有颗积极而焦虑的心，却远远没有行动
* 对很多概念都是“我以为”的知道，完全经不起别人的考验，别人一问就不知道怎么回答了，为什么不知道，因为其实从来没有好好思考过。
* 做正确的事情，坚持做。

### 3.未来半年计划
* 核心目标：整体目标就是调整自己的状态，不再如此疲惫。
* 落实方案
	* 每晚十点半睡觉，不带手机进入卧室
	* 每周更新一次Blog，暂时不限制内容，坚持频率
	* 尝试Fake it until you make it,周末就要去考试，练起来。
	* 理顺心性，结婚。
	* 了解一下“时间管理”，输出自己的理解，做出自己的实践
	* 用“把你的英语用起来”的方法学习英语，逼迫自己的方式就是报名雅思监考（2个月内完成）
	
#####要做的事情反反复复其实也就这么多，一直迷失在想去寻找捷径的路上，该停下来了。

**Comment by yanzhiw** [comment]
## 怼你哟~

**时间**：20180530 18:45-21:00

**事件**：ZoomQuiet 上海线下面基会

- top1：绝大多数人是为了解决问题而开始学习编程
  - 目的倒推动力。我之所以要去学习一件事情，比如编程，是因为我需要拥有这项技能去解决我现在所遇到的困难。如果在现实中找不到相应的环境，那么很可能这件事情对我来说并不是那么重要，自然而然动力就不足了。
  - 解决问题的方法有很多种，编程只是其中一种。如果我有性价比更高的简单的解决方案，那么复杂的方案坑就不适合我了。在考虑上马一种解决方案之前，我们所遇到的问题，很多都是别人已经遇到过的，善用搜索引擎，看一下别人是怎么解决的。
- top2：fake until you make it.
  - 所谓的**我对某事感兴趣**，实际上很多人表达的意思是**我想要做某事但是还没投入任何精力**。
  - 实际上我们说**我对某事感兴趣**至少应该包含两个层次：
    - 我在某事上投入了多少时间精力？
    - 我在这件事上的作品是什么？
  - 作品最好是所有人可见的可记录的公开作品，比如公开的发表等等。
- top3：如何对抗他人的错误观点？
  - 硬怼
  - 提高title，将自己包装成权威，让别人相信你。
    - 进一步思考，诉诸道德。岳不群的做法，将自己的武功等等道德化正义化，贬斥其他观点。
  - 实际上对抗错误观点本质上是在对抗我之前我之后的所有错误观点的总和。承认自己无能为力，仅仅可以在此时此刻改变一小部分人就可以了。



## 自我提升的方法

给自己写一本说明书，教过去的自己如何完成一件事，从而形成一套可复用的解决方案。

**Comment by erdongheng** [comment]
## 写在前面
线下聚会迷人在细节，可供多角度解读的细节。面基的事前、事中、事后，都有可供学习的细节点。

- 事前：大妈通过GitHub收集问题，碰面前一一浏览，部分直接回怼；

- 事中：对每段对话单独录音，以便回顾。悄无声息地给每个参与者特写一张（一张拍晃了再来一张），几分钟后发在小群里。这些事做得迅捷，丝毫没有扰乱谈话节奏。

- 事后：我才刚进家门，大妈就已经 1.上传活动命名清晰的录音 2.发送今天提及的点的文章链接 3.发布作业。说到录音文件命名，顺带提下大妈给录音文件命名的一例，20180530SH_4_fullstack_202138，分别是日期地点_序号（文件排序）_对话关键词_录音开始时刻。

## 回忆总结 get 到的嗯哼点
get到的嗯哼点，更多是用自己的语言写的，反映自己的理解，而不是最触动的原话，不知道与大妈要传递的重点是否一致。除了下面三点，还有正向反馈、正确分析问题，也是很重要的点。

### 1.解决问题，是学习动力，也是学习方式

- 你现在碰到的问题，如果不用编程也可以很有效地解决，为什么要学习编程？

- 不要为了学习而学习。找编程能解决的问题，比如开发一个微信小程序，碰到问题捡理论。

### 2.厘清基本概念和运用数据是分析问题的两大利器
- 基本概念
  - 文化 某位朋友说，因为中日文化不同，所以xxx。大妈问，什么是文化。
  - 编程（program） 学编程，那编程是什么
 
- 运用数据，融入到血液里的数据意识
  - 时间记录。大妈发了一张当日计时图片，是手机应用iTimeLog里的截图，这种计时方法在13年定型，坚持了5年，公开发布在怼圈，供分析对比。（0601下载了iTimeLog，还在摸索使用，追踪自己的常规行为及行为耗时，初感受不错）
  - 照片 接近一万张。
  - 谈话时间  回答每个人的问题各用多少分钟；谈话中，“单口”时间多少分钟；谈话结束时，大妈估计自己讲了5万字；
  - 引用数据  分析程序员的市场需求缺口，大学毕业生700万/年，其中计算机相关学生X万，但市场上依然有Y万的岗位找不到程序员；富士康员工数400万（百度搜索到是120万，和大妈记的有偏，但量级在那）
  - 拿手菜  大妈问F最拿手的菜是什么，答曰，土豆烧牛肉；又问做了多少次了，无答；拆分问，一个月做多少次菜，答曰X次；继续问，Y次里是否会做1次，答曰是；继续问，做饭多少年，答曰Z年。最后估算出总次数=(X/Y)* 12 *Z。

大数据能用于公司，能用于个人。今天的交流，让我意识到我的数据意识薄弱。为什么这么弱？我想到两个原因，一是我习惯假设人的行为波动极大，次数、频率估计的偏差大，记录意义不大。这一假设本身是有问题的。二是我对于记录的作用不清晰，只能在最粗的颗粒度上记录。比如，我知道我看电影的大致总量，但仅有这一个粗数据，细分到某一电影类别看过多少部，则答不上来，因为我没有对我看过的大多数电影打上类别标签。

### 3.全世界最适合你的编程教材，是你自己写出来的
- 教是最好的学。选择这句话作为第三个点，是因为它回答了想实践“教是最好的学”的新手常常会碰到的几个关键问题——教谁、教什么、怎么教。教的对象是几个月前还挣扎在泥潭里的自己，教的内容是自己想学的东西，教的方式是写本教材，可能同时是最烂也最好的教材。

- 教除了能促进学，还有其他意义吗？开智和怼圈，都提倡用作品说话。我曾自问，在社群里我能否用作品说话？我飞速自答，否。我知道的他们也知道，我不知道的他们也知道。我不知道他们也不知道的事，我也不知道怎么知道。但这句话很鼓励人，世界上已经有很多无法逾越的作品，我们明知如此也要写，对于某位读者来说，你的可以是最好的，但你得写。

 
## 针对当前想作的事儿，给出相应改进计划

- 在9月1日前写9篇不下千字的书评（待更新）

**Comment by leilayanhui** [comment]
交付 https://github.com/DebugUself/du4proto/wiki/180530DUmeetingSH
